# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mribo\OneDrive\Documents\6è quadri\Tower_Defense.py\Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 355)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 501, 331))
        self.label.setObjectName("label")
        self.PlayButton = QtWidgets.QPushButton(Form)
        self.PlayButton.setGeometry(QtCore.QRect(230, 130, 75, 23))
        self.PlayButton.setIconSize(QtCore.QSize(50, 50))
        self.PlayButton.setObjectName("PlayButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 421, 91))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><img src=\":/Principal/Fons 1.jpg\"/></p></body></html>"))
        self.PlayButton.setText(_translate("Form", "Play"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><img src=\":/Principal/Títol.jpg\"/></p></body></html>"))
import Imatges_rc
