# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mribo\OneDrive\Documents\6è quadri\Tower_Defense.py\Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from games.game1 import Juego





class MenuPrincipal(object):
    def __init__(self):
        self.speed = "Media"
        self.difficulty = "Media"

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 355)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 501, 331))
        self.label.setObjectName("label")
        self.PlayButton = QtWidgets.QPushButton(Form)
        self.PlayButton.setGeometry(QtCore.QRect(230, 130, 75, 23))
        self.PlayButton.setIconSize(QtCore.QSize(50, 50))
        self.PlayButton.setObjectName("PlayButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 421, 91))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.PlayButton.clicked.connect(lambda: self.closescr(Form))
        self.PlayButton.clicked.connect(self.run_game)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><img src=\"Imatges/Fons 1.jpg\"/></p></body></html>"))
        self.PlayButton.setText(_translate("Form", "Play"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><img src=\"Imatges/Títol.jpg\"/></p></body></html>"))

    def closescr(self, Form):
        Form.hide()

    def run_game(self):
        self.ui = MenuPrincipal()
        j = Juego(self.ui.speed, self.ui.difficulty)
        j.run()